apiVersion: fis.fis.dksshddl.dev/v1alpha1
kind: ExperimentTemplate
metadata:
  name: memory-stress-experiment
  namespace: default
spec:
  description: "Inject increasing memory load on nginx pods"
  
  targets:
  - name: nginx-pods
    namespace: default
    labelSelector:
      app: nginx
    selectionMode: ALL
  
  actions:
  - name: low-memory-stress
    type: pod-memory-stress
    duration: 5m
    target: nginx-pods
    parameters:
      percent: "80"
  
  - name: medium-memory-stress
    type: pod-memory-stress
    duration: 5m
    target: nginx-pods
    parameters:
      percent: "90"
    startAfter:
    - low-memory-stress
  
  - name: high-memory-stress
    type: pod-memory-stress
    duration: 5m
    target: nginx-pods
    parameters:
      percent: "100"
    startAfter:
    - medium-memory-stress
  
  stopConditions:
  - source: none
  
  tags:
  - key: Name
    value: "EKS Stress: Memory"
  - key: Environment
    value: "test"
