apiVersion: fis.fis.dksshddl.dev/v1alpha1
kind: Experiment
metadata:
  labels:
    app.kubernetes.io/name: aws-fis-controller
  name: onetime-disk-stress-count
spec:
  # Reference ExperimentTemplate by name (cluster-scoped)
  experimentTemplate:
    name: "low-disk-stress-experiment-count"
  
  # No schedule = one-time execution (Job mode)
  # Experiment will start immediately when created
  
  tags:
    - key: "Environment"
      value: "test"
    - key: "Type"
      value: "one-time"
